#!/bin/bash

source /usr/local/JSBach/conf/variables.conf

######################################################################
###  Funcions
######################################################################

fnc_iniciar()
{
	fnc_aturar > /dev/null 2>&1 
	echo "Iniciant tallafocs"	
		
	
	for linia in $(grep -v '#' "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"); do
	    nom=$(echo "$linia"|cut -d';' -f1)
	    ip=$(echo "$linia"|cut -d';' -f3)
	    iptables -N $nom
	    iptables -A FORWARD -s $ip -j $nom	    
	done
	
	iptables -N ports_wls
	for linia in $(grep -v '#' "$DIR/$PROJECTE/$DIR_CONF/$PORTS_WLS"); do
	    protocol=$(echo "$linia"|cut -d';' -f1)
	    num_port=$(echo "$linia"|cut -d';' -f2)
	    iptables -A ports_wls -p $protocol --dport $num_port -j ACCEPT	    
	done
	iptables -A ports_wls -j DROP
	
}

fnc_aturar()
{
	echo "Aturar tallafocs"
	iptables -F
	iptables -X
	iptables -P FORWARD ACCEPT
	iptables -P INPUT ACCEPT
	iptables -P OUTPUT ACCEPT
	
	
	resultat=$($DIR/$PROJECTE/$DIR_SCRIPTS/enrutar estat)

	# Comprovem si conté la paraula "ACTIVAT"
	echo "$resultat" | grep -q "$ACTIVAT"

	if [ $? -eq 0 ]; then
		iptables -t nat -F 
		iptables -t nat -X
		$DIR/$PROJECTE/$DIR_SCRIPTS/enrutar iniciar > /dev/null 2>&1 
	else
		iptables -t nat -F 
		iptables -t nat -X
	fi	
}


fnc_configurar()
{		
	echo "Configuracio"
	
	ARG_1=$1
	shift
			
	# Fem switch per executar la funció que toca
	case "$ARG_1" in
	  desconnectar)
	        linia=$(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
	        vid=$( echo $linia | cut -d';' -f2)
	        if [ -z "$nom" ]; then
		    echo "Error no existeix vlan $1"
		else
		    iptables -F $nom
		        # IPs privilegiades
		     	for ipwls in $(grep -v '#' "$DIR/$PROJECTE/$DIR_CONF/$IPS_WLS"| grep "^$vid;"); do
			    ip=$(echo "$ipwls"|cut -d';' -f2)
			    mac=$(echo "$ipwls"|cut -d';' -f3)
			    iptables -A $nom   -s $ip -m mac --mac-source $mac -j ACCEPT 
			done

		    iptables -A $nom -j DROP
		fi
	  	;;
	  connectar)
	        linia=$(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
	        if [ -z "$nom" ]; then
		    	echo "Error no existeix vlan $1"
		else
			iptables -F $nom
		fi	        
	  	;;
          connectar_port_wls)
	        linia=$(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
	        vid=$( echo $linia | cut -d';' -f2)
	        if [ -z "$nom" ]; then
		    	echo "Error no existeix vlan $1"
		else
			iptables -F $nom
		 	# IPs privilegiades
			for ipwls in $(grep -v '#' "$DIR/$PROJECTE/$DIR_CONF/$IPS_WLS"| grep "^$vid;"); do
			    ip=$(echo "$ipwls"|cut -d';' -f2)
			    mac=$(echo "$ipwls"|cut -d';' -f3)
			    iptables -A $nom   -s $ip -m mac --mac-source $mac -j ACCEPT 
			done
			
			iptables -A $nom -j ports_wls
			
		fi	        
	  	;;
	  afegir_port_wls)
	  	echo "$1;$2;" >> "$DIR/$PROJECTE/$DIR_CONF/$PORTS_WLS"
	        ;;
	  eliminar_port_wls)
	        PROTO="$1"
		PORT="$2"
		sed -i "/^${PROTO};${PORT};$/d" "$DIR/$PROJECTE/$DIR_CONF/$PORTS_WLS"
	        ;;  
	  afegir_ip_wls)
	  	echo "$1;$2;$3;" >> "$DIR/$PROJECTE/$DIR_CONF/$IPS_WLS"
	        ;;
	  eliminar_ip_wls)
	        VID="$1"
		IP="$2"
		MAC="$3"
		sed -i "/^${VID};${IP};${MAC};$/d" "$DIR/$PROJECTE/$DIR_CONF/$IPS_WLS"
	        ;;    
	  *)
	        echo "Error  argumnets conectar, desconectar"
	        ;;
	esac	
	
}


fnc_estat()
{	
	if [ $# -eq 0 ]; then
		 #echo "$ACTIVAT"
		 #echo "$DESACTIVAT"
		 echo MAIN
		 iptables -nvL --line-numbers
		 echo
		 echo
		 echo NAT	 
		 iptables -t nat -nvL --line-numbers
		 exit 1
	fi
	
	        linia=$(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
	        if [ -z "$nom" ]; then
		    echo "Error no existeix vlan $1"
		else
		     	if iptables -C $nom -j DROP 2>/dev/null; then
			    echo "DESCONNECTADA"
			else
			    if iptables -C $nom -j ports_wls  2>/dev/null; then
				echo "CONNECTADA PORT WLS"
			    else
			    	echo "CONNECTADA"
			    fi
			fi 
		fi
}


######################################################################
###  MAIN
######################################################################

MSG="falta [iniciar, aturar, configurar ,estat]"

# Comprovem que hi hagi almenys un argument (la opció)
if [ $# -lt 1 ]; then
  echo "$MSG"
  exit 1
fi

OPCIO_1=$1
shift

# Fem switch per executar la funció que toca
case "$OPCIO_1" in
  iniciar)
    fnc_iniciar  $@
    ;;
  aturar)
    fnc_aturar	$@
    ;; 
  configurar) 
    fnc_configurar $@
    ;;
  estat) 
    fnc_estat $@
    ;;
  *)
    echo "$MSG"
    ;;
esac


