#!/bin/bash

SCRIPTS_DIR="/usr/local/LosChichos/scripts"
while true; do
  # Mostrar prompt i llegir entrada de l'usuari
  echo -n "LosChichos> "
  read input_line

  #Comprobar ?
  if [ "$input_line" = "?" ]; then
    ls $SCRIPTS_DIR
    continue
  fi

  #Comprobar que no es scr_cli
  #if [ "$input_line" = "scr_cli" ]; then       Ya no es necesario
  #  continue
  #fi
  
  # Comprovar si l'usuari vol sortir
  if [ "$input_line" = "exit" ]; then
    break
  fi

  # Separar la línia en array d'arguments
  # Utilitzem 'read -a' per separar per espais
  read -a args <<< "$input_line"

  # Comprovar que s'ha introduït almenys un argument (nom del script)
  if [ ${#args[@]} -lt 1 ]; then
    continue
  fi

  SCRIPT_NAME="${args[0]}"
  SCRIPT_PATH="$SCRIPTS_DIR/$SCRIPT_NAME"

  # Arguments restants per passar al script
  SCRIPT_ARGS=("${args[@]:1}")

  # Comprovar que el script existeix i és executable
  if [ ! -x "$SCRIPT_PATH" ]; then
    echo "Error: El script '$SCRIPT_NAME' no existe o no es ejecutable a $SCRIPTS_DIR."
    continue
  fi

  # Executar el script amb els arguments
  "$SCRIPT_PATH" "${SCRIPT_ARGS[@]}"
done

