#!/bin/bash

SCRIPTS_DIR="/usr/local/LosChichos/scripts"

set +o notify
trap '' HUP

# Fuerza a que bash envíe cada línea sin buffer
export LC_ALL=C
export LANG=C
# Desactiva el buffer de stdout

perl -e 'select STDOUT; $| = 1;'



source /usr/local/LosChichos/system/auth.lib

# Authentication Loop
while true; do
  echo -n "Username: "
  read username
  echo -n "Password: "
  read password
  
  if [ "$username" == "SESSION_AUTH" ]; then
      if validate_session "$password"; then
          # Extraer usuario real del archivo de sesión
          # Sabemos que el token es válido, por lo que el archivo existe
          SESSION_FILE="$SESSION_DIR/$password"
          REAL_USER=$(sed -n '1p' "$SESSION_FILE")
          #echo "Login correcto. Bienvenido $REAL_USER (via session)!"
          break
      else
          echo "Login fallido. Sesión inválida."
      fi
  elif check_credentials "$username" "$password"; then
      echo "Login correcto. Bienvenido $username!"
      break
  else
      echo "Login fallido. Intente de nuevo."
  fi
done

while true; do
  # Mostrar prompt y leer entrada del usuario
  echo -n "LosChichos> "
  read input_line

  #Comprobar ?
case "$input_line" in
  "?")
    ls "$SCRIPTS_DIR"
    continue
    ;;
  "exit")
    break
    ;;
esac

  # Separar la línea en array de argumentos
  # Utilitzamos 'read -a' para separar por espacios
  read -a args <<< "$input_line"

  # Comprobar que se ha introducido al menos un argumento (nombre del script)
  if [ ${#args[@]} -lt 1 ]; then
    continue
  fi

  SCRIPT_NAME="${args[0]}"
  SCRIPT_PATH="$SCRIPTS_DIR/$SCRIPT_NAME"

  # Arguments restants per passar al script
  SCRIPT_ARGS=("${args[@]:1}")

  # Comprovar que el script existeix i és executable
  if [ ! -x "$SCRIPT_PATH" ]; then
    echo "Error: El script '$SCRIPT_NAME' no existe o no es ejecutable a $SCRIPTS_DIR."
    continue
  fi

  # Executar el script amb els arguments
  "$SCRIPT_PATH" "${SCRIPT_ARGS[@]}"
done

