#!/bin/bash
echo "Content-type: text/html; charset=utf-8"
echo ""

/bin/cat << EOM
<html>
<head>
  <meta charset="utf-8">
  <title>Hola món CGI</title>
</head>
<body>
EOM

echo "Resultat de enrutar <br>"

echo "$(/usr/local/JSBach/scripts/client_srv_cli enrutar estat) <br>"

echo "JA funciona!!!!!"

/bin/cat << EOM
</body>
</html>
EOM



