#!/bin/bash

source /usr/local/LosChichos/conf/variables.conf
source $DIR/$PROJECTO/$DIR_CONF/$FUNC

######################################################################
###  Funcions
######################################################################

fnc_iniciar()
{
    if fnc_enp_status "br0"; then
        echo "El servei ja està actiu"
        exit 1
    fi
    
	echo "Iniciar"
	
	### FALTA ESTAT BRIDGE PER NO INICIAR SI JA ESTA FUNCIONANT
	
	##CREAR  BRIDGE part interna
	ip l a name br0 type bridge vlan_filtering 1
	ip l s dev br0 up
	
	for LINIA in $(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF" | grep -v '^#'); do
	    VLANID=$(echo "$LINIA"|cut -d';' -f2)
	    VLANIP=$(echo "$LINIA"|cut -d';' -f4)
	    ip l a l  br0 name br0.$VLANID  type vlan id $VLANID
	    ip l s dev br0.$VLANID up
	    ip a a dev br0.$VLANID $VLANIP
	done
	
	#Bridge part LAN
	bridge vlan del dev br0 vid 1 pvid untagged self
	for LINIA in $(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_IF" | grep -v '^#'); do
	 	NOM_IF=$(echo "$LINIA"|cut -d';' -f1)
	 	VLAN_UNTAG=$(echo "$LINIA"|cut -d';' -f2)
	 	VLAN_TAG=$(echo "$LINIA"|cut -d';' -f3)
        WAN_IF=$(ip route show default | awk '/default/ {print $5}')
        case "$NOM_IF" in # Esto es para no añadir la interfaz de salida al bridge, y el propio bridge
        br0|"$WAN_IF")
            continue
            ;;
        *)
            ip l s dev "$NOM_IF" master br0
            ;;
        esac
	 	bridge vlan del dev $NOM_IF vid 1 pvid untagged	
	 	if [ "$VLAN_UNTAG" != "0" ]; then
	 		bridge vlan add dev $NOM_IF vid $VLAN_UNTAG pvid untagged
	 		bridge vlan add dev br0 vid $VLAN_UNTAG self
	 	fi
	 	if [ "$VLAN_TAG" != "0" ]; then
	 		for CAMP in ${VLAN_TAG//,/ }; do
	 			bridge vlan add dev $NOM_IF vid $CAMP 
	 			bridge vlan add dev br0 vid $CAMP self
			done
	 	fi	 	 	
	done
	
	
}

fnc_aturar()
{
	echo "Parar"
	ip l d dev br0
}


fnc_configurar()
{	
	
	if [ $# -lt 1 ]; then
        echo "Uso : $0 conf [mostrar, guardar, borrar]"
        exit 1
    fi
    ARG1=$1
    shift
    case "$ARG1" in
        show | mostrar)
            if [ "$1" == "vlan" ]; then
              cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF" | grep -v '^#'
            fi
            if [ "$1" == "bridge" ]; then
              cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_IF" | grep -v '^#'
            fi
        ;;
        save | guardar)
            OPCIO_2=$1
            shift
            case "$OPCIO_2" in
                vlan)
                    if fnc_validar_ip_mascara "$3"; then
                        R_VLAN=$3
                    else
                        echo "Error: La IP y máscara de red '$3' no es válida."
                        exit 1
                    fi
                    if fnc_validar_ip_mascara "$4"; then
                        GW_VLAN=$4
                    else
                        echo "Error: La IP y máscara de gateway '$4' no es válida."
                        exit 1
                    fi

                    RESULTADO=$(grep -v ";$2;" "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF")
                    echo "$RESULTADO" > "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"
                    echo "$1;$2;$R_VLAN;$GW_VLAN;" >> "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"
                    RESULTADO1=$(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF")
                    echo "$RESULTADO1"
                ;;
                bridge)
                    
                    if ! ip link show "$1" &>/dev/null; then
                        echo "Error: la interfaz '$1' no existe en el sistema."
                        echo "Interfaces disponibles:"
                        ls /sys/class/net
                        exit 1
                    fi

                    #RESULTADO=$(grep -v ";$1;" "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_IF")
                    #echo "$RESULTADO" > "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_IF"
                    #echo "$1;$2;$3;" >> "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_IF"

                    sed -i "/$1;/d" "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_IF"
                    echo $@ | sed 's/ /;/g' >> "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_IF"
                    cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_IF"
                ;;
                *)
                echo "error: opción no válida. Usa 'vlan' o 'bridge'."
                exit 1
                ;;
            esac
    
        ;; 
        delete | borrar) 
            if [ "$1" == "vlan" ]; then
                if [ "$2" -le 2 ]; then
                    echo "No se puede borrar la vlan $2"
                    exit 1
                fi
                RESULTADO=$(grep -v ";$2;" "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF")
                echo "$RESULTADO" > "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"
                echo "$RESULTADO"
            fi
        ;;
        *)
        echo "error: opción no válida. Usa 'mostrar', 'guardar' o 'borrar'."
        exit 1
        ;;
        esac

}


fnc_estat()
{
	if fnc_enp_status "br0"; then
        echo "$ACTIVADO"
        for LINIA in $(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF" | grep -v '^#'); do
            VLANID=$(echo "$LINIA"|cut -d';' -f2)
            ip -4 -br a show dev br0.$VLANID
        done
        bridge vlan show
    else
        echo "$DESACTIVADO"
    fi
    
}


######################################################################
###  MAIN
######################################################################

MSG="USO: $0 [start, stop, conf, status]"

# Comprovem que hi hagi almenys un argument (la opció)
if [ $# -lt 1 ]; then
  echo "$MSG"
  exit 1
fi

OPCIO_1=$1
shift

# Fem switch per executar la funció que toca
case "$OPCIO_1" in
  start | iniciar)
    fnc_iniciar  $@
    ;;
  stop | aturar)
    fnc_aturar	$@
    ;; 
  conf | configurar) 
    fnc_configurar $@
    ;;
  status | estat) 
    fnc_estat $@
    ;;
  *)
    echo "$MSG"
    ;;
esac

