#!/bin/bash

source /usr/local/JSBach/conf/variables.conf

######################################################################
###  Funcions
######################################################################

fnc_iniciar()
{
	echo "Iniciar"
	
	### FALTA ESTAT BRIDGE PER NO INICIAR SI JA ESTA FUNCIONANT
	
	##CREAR  BRIDGE part interna
	ip l a name br0 type bridge vlan_filtering 1
	ip l s dev br0 up
	
	for LINIA in $(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF" | grep -v '^#'); do
	    VLANID=$(echo "$LINIA"|cut -d';' -f2)
	    VLANIP=$(echo "$LINIA"|cut -d';' -f4)
	    ip l a l  br0 name br0.$VLANID  type vlan id $VLANID
	    ip l s dev br0.$VLANID up
	    ip a a dev br0.$VLANID $VLANIP
	done
	
	#Bridge part LAN
	bridge vlan del dev br0 vid 1 pvid untagged self
	for LINIA in $(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_IF" | grep -v '^#'); do
	 	NOM_IF=$(echo "$LINIA"|cut -d';' -f1)
	 	VLAN_UNTAG=$(echo "$LINIA"|cut -d';' -f2)
	 	VLAN_TAG=$(echo "$LINIA"|cut -d';' -f3)
	 	ip l s dev $NOM_IF master br0
	 	bridge vlan del dev $NOM_IF vid 1 pvid untagged	
	 	if [ ! -z $VLAN_UNTAG ]; then
	 		bridge vlan add dev $NOM_IF vid $VLAN_UNTAG pvid untagged
	 		bridge vlan add dev br0 vid $VLAN_UNTAG self
	 	fi
	 	if [ ! -z $VLAN_TAG ]; then
	 		for CAMP in ${VLAN_TAG//,/ }; do
	 			bridge vlan add dev $NOM_IF vid $CAMP 
	 			bridge vlan add dev br0 vid $CAMP self
			done
	 	fi	 	 	
	done
	
	
}

fnc_aturar()
{
	echo "Aturar"
	ip l d dev br0
}


fnc_configurar()
{	
	
	echo "Configuracio guardada"
}


fnc_estat()
{
	 echo "$ACTIVADO"
	 echo "$DESACTIVADO"	    
}


######################################################################
###  MAIN
######################################################################

MSG="falta [iniciar, aturar, configurar ,estat]"

# Comprovem que hi hagi almenys un argument (la opció)
if [ $# -lt 1 ]; then
  echo "$MSG"
  exit 1
fi

OPCIO_1=$1
shift

# Fem switch per executar la funció que toca
case "$OPCIO_1" in
  start | iniciar)
    fnc_iniciar  $@
    ;;
  stop | aturar)
    fnc_aturar	$@
    ;; 
  stop | configurar) 
    fnc_configurar $@
    ;;
  status | estat) 
    fnc_estat $@
    ;;
  *)
    echo "$MSG"
    ;;
esac

