#!/bin/bash

source /usr/local/LosChichos/conf/variables.conf
source $DIR/$PROJECTO/$DIR_CONF/$FUNC

######################################################################
###  Funcions
######################################################################

fnc_iniciar() {
	if [[ "$(/usr/local/LosChichos/system/nc_client "bridge estat")" =~ ^$DESACTIVADO ]]; then
		echo "bridge no esta en execucio"
		return
	fi

	if systemctl is-active --quiet dnsmasq; then
		echo "dnsmasq ja esta en execucio"
		return
	fi

	echo "Iniciar"
	if  [ $(grep -v "^#" $DIR/$PROJECTO/$DIR_CONF/$DHCP_CONF | wc -l) -eq 0 ]; then
		fnc_crear_fitxer_conf
	fi
	fnc_crear_dnsmasq_conf

	systemctl start dnsmasq

	fnc_estat
}

fnc_crear_dnsmasq_conf() {

    echo "creant fitxer de configuracio"
    fitxer_conf="/etc/dnsmasq.conf"

    echo "# Configuració generada automàticament" > "$fitxer_conf"
    echo "bind-interfaces" >> "$fitxer_conf"
    echo "port=53" >> "$fitxer_conf"

    # No escoltar en WAN
    echo "except-interface=wan0" >> "$fitxer_conf"

    # Usar DNS que rep la WAN per DHCP
    echo "resolv-file=/run/systemd/resolve/resolv.conf" >> "$fitxer_conf"

    for LINIA in $(grep -v "^#" "$DIR/$PROJECTO/$DIR_CONF/$DHCP_CONF")
    do
        DHCP_VID=$(echo "$LINIA" | cut -d';' -f1)
        DHCP_INICI=$(echo "$LINIA" | cut -d';' -f2)
        DHCP_FINAL=$(echo "$LINIA" | cut -d';' -f3)
        DHCP_GATEWAY=$(echo "$LINIA" | cut -d';' -f4)
        DHCP_DNS1=$(echo "$LINIA" | cut -d';' -f5)
        DHCP_ACTIVAT=$(echo "$LINIA" | cut -d';' -f6)

        if [[ "$DHCP_ACTIVAT" == "$ACTIVADO" ]]; then
            echo "interface=br0.$DHCP_VID" >> "$fitxer_conf"
            echo "dhcp-range=interface:br0.$DHCP_VID,$DHCP_INICI,$DHCP_FINAL,12h" >> "$fitxer_conf"
            echo "dhcp-option=interface:br0.$DHCP_VID,3,$DHCP_GATEWAY" >> "$fitxer_conf"
            echo "dhcp-option=interface:br0.$DHCP_VID,6,$DHCP_DNS1" >> "$fitxer_conf"
        fi
    done

	# Configuracio wifi
	{
		source "$DIR/$PROJECTO/$DIR_CONF/$WIFI_CONF"
		
		if [[ "$wifi_dhcp_actiu" == "$ACTIVADO" ]]; then
			source "$DIR/$PROJECTO/$DIR_CONF/$WIFI_HOSTAPD_CONF"
			echo "interface=$interface" >> "$fitxer_conf"
			echo "dhcp-range=interface:$interface,$wifi_ip_inicial,$wifi_ip_final,12h" >> "$fitxer_conf"
			echo "dhcp-option=interface:$interface,3,$wifi_gateway" >> "$fitxer_conf"
			echo "dhcp-option=interface:$interface,6,$wifi_ip_dns1" >> "$fitxer_conf"
		fi
	}

    echo "log-dhcp" >> "$fitxer_conf"
    echo "log-queries" >> "$fitxer_conf"

    echo "Configuració de dnsmasq creada a $fitxer_conf"
}



fnc_aturar() {
	if ! systemctl is-active --quiet dnsmasq; then
		echo "dnsmasq no esta en execucio"
		return
	fi
	systemctl stop dnsmasq
	if [ $# -eq 0 ]; then
		echo "dnsmasq aturat"
	fi
}

fnc_crear_fitxer_conf() {

	for LINIA in $(cat "$DIR/$PROJECTO/$DIR_CONF/$DHCP_CONF" | grep -v '^#'); do
		VLANID=$(echo "$LINIA" | cut -d';' -f1)
		if ! grep ";$VLANID;" "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF" > /dev/null; then
			sed -i "s/^$VLANID;.*$/$NOVA_LINIA/" "$DIR/$PROJECTO/$DIR_CONF/$DHCP_CONF"
		fi
	done
	
	for LINIA in $(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF" | grep -v '^#'); do
		VLANID=$(echo "$LINIA" | cut -d';' -f2)
		if ! grep "^$VLANID;" "$DIR/$PROJECTO/$DIR_CONF/$DHCP_CONF" > /dev/null; then
			VLAN_IP=$(echo "$LINIA" | cut -d';' -f3)
			VLAN_IP_PE=$(echo "$LINIA" | cut -d';' -f4|cut -d'/' -f1)
			PRIMERA_IP=$(fnc_primera_ip_de_host "$VLAN_IP")
			DARRERA_IP=$(fnc_darrera_ip_de_host "$VLAN_IP")
			echo "$VLANID;$PRIMERA_IP;$DARRERA_IP;$VLAN_IP_PE;8.8.8.8;$DESACTIVADO;" >> $DIR/$PROJECTO/$DIR_CONF/$DHCP_CONF
		fi
	done
}

fnc_guardar_conf() {
	if [ $# -ne 6 ]; then
		echo "falta [vid, inici, final, gateway, dns1, activat]"
		return 1
	fi
	
	if  [ $(grep -v "^#" $DIR/$PROJECTO/$DIR_CONF/$DHCP_CONF | wc -l) -eq 0 ]; then
		fnc_crear_fitxer_conf
	fi

	vid=$1
	VLAN_INFO=$(grep ";$vid;" $DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF)
	if [ -z "$VLAN_INFO" ]; then
		echo "vlan id $vid no existeix"
		return 1
	fi	
	VLAN_IP=$(echo "$VLAN_INFO" | cut -d';' -f3)
	VLAN_MASC=$(echo "$VLAN_IP" | cut -d'/' -f2)
		
	inici=$2
	if ! fnc_validar_ip_host "$inici/$VLAN_MASC" && ! fnc_validar_mateixa_xarxa "$inici/$VLAN_MASC" "$VLAN_IP"; then
		echo "ip inici $inici/$VLAN_MASC  $VLAN_IP no valid"
		return 1
	fi
	final=$3
	if ! fnc_validar_ip_host "$final/$VLAN_MASC" && ! fnc_validar_mateixa_xarxa "$final/$VLAN_MASC" "$VLAN_IP"; then
		echo "ip final $final no valid"
		return 1
	fi
	if ! fnc_validar_ip1_menor_ip2 "$inici/$VLAN_MASC" "$final/$VLAN_MASC"; then
		echo "ip final $final no es major que ip inici $inici"
		return 1	
	fi
	gateway=$4
	if ! fnc_validar_ip_host "$gateway/$VLAN_MASC" && ! fnc_validar_mateixa_xarxa "$gateway/$VLAN_MASC" "$VLAN_IP"; then
		echo "ip gateway $gateway no valid "
		return 1
	fi
	dns1=$5
	if ! fnc_validar_ip "$dns1"; then
		echo "ip dns1 $dns1 no valid"
		return 1
	fi
	activat=$6
	if [[ "$activat" != "$ACTIVADO" && "$activat" != "$DESACTIVADO" ]]; then
		echo "activat $activat no valid"
		return 1
	fi

	NOVA_LINIA="$vid;$inici;$final;$gateway;$dns1;$activat;"
	sed -i "s/^$vid;.*$/$NOVA_LINIA/" "$DIR/$PROJECTO/$DIR_CONF/$DHCP_CONF"
	echo " Configuracio guardada correctament"
}


fnc_mostrar_conf() {
	fnc_crear_fitxer_conf
	grep -v "^#" "$DIR/$PROJECTO/$DIR_CONF/$DHCP_CONF"
}

fnc_configurar() {
	local ACCIO=$1
	shift

	case "$ACCIO" in
		"mostrar_conf")
			fnc_mostrar_conf
			;;
		"mostrar_wifi_conf")
			$DIR/$PROJECTO/$DIR_SCRIPTS/wifi configurar mostrar_wifi_conf
			;;
		"guardar_conf")
			fnc_guardar_conf $@
			;;
		"guardar_wifi_conf")
			source "$DIR/$PROJECTO/$DIR_CONF/$WIFI_CONF"
			$DIR/$PROJECTO/$DIR_SCRIPTS/wifi configurar guardar_wifi_conf $@ "$wifi_portal_captiu"
			;;
		*)
			echo "falta [mostrar_conf, mostrar_wifi_conf, guardar_conf]"
			;;
	esac
}

fnc_estat() {
	if systemctl is-active --quiet dnsmasq; then
		echo "$ACTIVADO"
		echo ""
		echo "Fitxer de configuracio"
		echo ""
		cat /etc/dnsmasq.conf
	else
		echo "$DESACTIVADO"
	fi
}

######################################################################
###  MAIN
######################################################################

MSG="falta [iniciar, aturar, configurar ,estat]"

# Comprovem que hi hagi almenys un argument (la opció)
if [ $# -lt 1 ]; then
	echo "$MSG"
	exit 1
fi

OPCIO_1=$1
shift

# Fem switch per executar la funció que toca
case "$OPCIO_1" in
iniciar)
	fnc_iniciar $@
	;;
aturar)
	fnc_aturar $@
	;;
configurar)
	fnc_configurar $@
	;;
estat)
	fnc_estat $@
	;;
*)
	echo "$MSG"
	;;
esac
