#!/bin/bash
source /usr/local/LosChichos/conf/variables.conf
source $DIR/$PROJECTO/$DIR_CONF/$FUNC


####################################
## Script de Enrrutamiento de Red ##
####################################



#########################################################
## Funciones 
#########################################################
enp=$(ip route show default | awk '/default/ {print $5}')
fnc_enr_start(){
    if [ $(cat /proc/sys/net/ipv4/ip_forward) -eq 1 ] && iptables -t nat -C POSTROUTING -o "$enp" -j MASQUERADE 2> /dev/null; then
        echo "El enrutamiento ya está activado"
        exit 1
    fi
    echo 1 > /proc/sys/net/ipv4/ip_forward
    iptables -t nat -A POSTROUTING -o $enp -j MASQUERADE
    echo "$ACTIVADO"
}

fnc_enr_start_nat(){
    if iptables -t nat -C POSTROUTING -o "$enp" -j MASQUERADE 2> /dev/null; then
        echo "La NAT ya está activada"
        exit 1
    fi
    iptables -t nat -A POSTROUTING -o $enp -j MASQUERADE
    echo "$ACTIVADO"
}

fnc_enr_start_enr(){
    if [ $(cat /proc/sys/net/ipv4/ip_forward) -eq 1 ]; then
        echo "El enrutamiento ya está activado"
        exit 1
    fi
    echo 1 > /proc/sys/net/ipv4/ip_forward
    echo "$ACTIVADO"
}

fnc_enr_stop(){
    echo "$DESACTIVADO"
    echo 0 > /proc/sys/net/ipv4/ip_forward
    iptables -t nat -D POSTROUTING -o $enp -j MASQUERADE
}

fnc_enr_stop_nat(){
    iptables -t nat -D POSTROUTING -o $enp -j MASQUERADE
    echo "$DESACTIVADO"
}

fnc_enr_stop_enr(){
    echo 0 > /proc/sys/net/ipv4/ip_forward
    echo "$DESACTIVADO"
}


fnc_enr_status(){
    echo "Estado del Enrutamiento: "
    if [ $(cat /proc/sys/net/ipv4/ip_forward) -eq 1 ] && sudo iptables -t nat -C POSTROUTING -o "$enp" -j MASQUERADE 2> /dev/null; then
        echo "$ACTIVADO"
    else
        echo "$DESACTIVADO"
    fi
    exit 1

}

fnc_enr_status_completo(){
    echo "Etado del Enrutamiento: "
    if [ $(cat /proc/sys/net/ipv4/ip_forward) -eq 1 ]; then
        echo "$ACTIVADO"
    else
        echo "$DESACTIVADO"
    fi

    echo "Estado de la NAT: "
    if iptables -t nat -C POSTROUTING -o "$enp" -j MASQUERADE 2> /dev/null; then
        echo "$ACTIVADO"
    else
        echo "$DESACTIVADO"
    fi
}

#####################################################
## MAIN
#####################################################

MSG2="Uso: $0 [start,stop,status]"


# comprovación numero de argumentos
if [ $# -lt 1 ]; then
    echo "$MSG2"
    exit 1
fi




case $1 in
    start)
        estadoifwan=$(fnc_ifwan_status)
        if [ "$estadoifwan" == "$DESACTIVADO" ]; then
            echo "El servicio ifwan está Parado"
            echo "Ejecutalo con ./ifwan"
            exit 1
        fi
        fnc_enr_start 
        ;;
    startNAT)
        estadoifwan=$(fnc_ifwan_status)
        if [ "$estadoifwan" == "$DESACTIVADO" ]; then
            echo "El servicio ifwan está Parado"
            echo "Ejecutalo con ./ifwan"
            exit 1
        fi
        fnc_enr_start_nat
        ;;
    startENR)
        fnc_enr_start_enr
        ;;
    stop)
        fnc_enr_stop 
        ;;
    stopNAT)
        fnc_enr_stop_nat
        ;;
    stopENR)
        fnc_enr_stop_enr
        ;;
    status)
        fnc_enr_status 
        exit 0
        ;;
    statusCOMPLETO)
        fnc_enr_status_completo
        exit 0
        ;;
    *)
        echo "$MSG2"
        exit 1
        ;;
esac