#!/bin/bash

source /usr/local/LosChichos/conf/variables.conf

CONFIG=$(cd "$DIR"/"$PROJECTO"/"$DIR_SCRIPTS"/ && ./ifwan conf mostrar)
conf_mode=$(echo "$CONFIG" | tr -s ' ' | cut -d' '  -f1 )
conf_int=$(echo "$CONFIG" | tr -s ' ' | cut -d' '  -f2 )
if [[ "$conf_mode" == "manual" ]] then
	conf_ip=$(echo "$CONFIG" | tr -s ' ' | cut -d' '  -f3 )
	conf_masc=$(echo "$CONFIG" | tr -s ' ' | cut -d' '  -f4 )
	conf_pe=$(echo "$CONFIG" | tr -s ' ' | cut -d' '  -f5 )
	conf_dns=$(echo "$CONFIG" | tr -s ' ' | cut -d' ' -f6 )
fi

echo $conf_mode
echo $conf_int
echo $conf_ip
echo $conf_masc
echo $conf_pe
echo $conf_dns

