#!/bin/bash
source /usr/local/LosChichos/conf/variables.conf
source $DIR/$PROJECTO/$DIR_CONF/$FUNC

num1=1
num2=2.5
str1="Hola"

for var in "$num1" "$num2" "$str1"; do
	if fnc_es_num "$var"; then
		echo "'$var' es un valor numérico."
	else
		echo "'$var' NO es un valor numérico."
	fi
done

fnc_escribir_vivo "Pobando......." 0.1