#!/bin/bash

source /usr/local/LosChichos/conf/variables.conf


######################################################################
###  Funcions
######################################################################

fnc_iniciar()
{
	fnc_aturar >/dev/null 2>&1
	echo "Iniciar"	
		
	
	for linia in $(grep -v '#' "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"); do
	    nom=$(echo "$linia"|cut -d';' -f1)
	    ip=$(echo "$linia"|cut -d';' -f3)
	    iptables -N $nom
	    iptables -A FORWARD -s $ip -j $nom	    
	done
	
}

fnc_aturar()
{
	echo "Aturar"
	iptables -F
	iptables -X
	iptables -P FORWARD ACCEPT
	iptables -P INPUT ACCEPT
	iptables -P OUTPUT ACCEPT
	
	
	resultat=$(cd $DIR/$PROJECTO/$DIR_SCRIPTS/ && ./enrutar status)

	# Comprovem si conté la paraula "ACTIVAT"
	echo "$resultat" | grep -q "$ACTIVADO"

	if [ $? -eq 0 ]; then
		iptables -t nat -F 
		iptables -t nat -X
		cd $DIR/$PROJECTO/$DIR_SCRIPTS/ && ./enrutar start
	else
		iptables -t nat -F 
		iptables -t nat -X
	fi	
}


fnc_configurar()
{	
	
	echo "Configuracio"
	
	ARG_1=$1
	shift
			
	# Fem switch per executar la funció que toca
	case "$ARG_1" in
	  desconnectar)
	        linia=$(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
	        if [ -z "$nom" ]; then
		    echo "Error no existeix vlan $1"
		else
		    iptables -F $nom
		    iptables -A $nom -j DROP
		fi
	  	;;
	  connectar)
	        linia=$(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
	        if [ -z "$nom" ]; then
		    	echo "Error no existeix vlan $1"
		else
			iptables -F $nom
		fi	        
	  	;;
	  *)
	        echo "Error  argumnets conectar, desconectar"
	        ;;
	esac	
	
}


fnc_estat()
{	
	if [ $# -eq 0 ]; then
		 #echo "$ACTIVAT"
		 #echo "$DESACTIVAT"
		 echo MAIN
		 iptables -nvL --line-numbers
		 echo
		 echo
		 echo NAT	 
		 iptables -t nat -nvL --line-numbers
		 exit 1
	fi
	
	        linia=$(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
	        if [ -z "$nom" ]; then
		    echo "Error no existeix vlan $1"
		else
			if ! sudo iptables -L "$nom" -n >/dev/null 2>&1; then
    			echo "Error: no existe la cadena de reglas"
    			exit 1
			fi
		    if sudo iptables -C $nom -j DROP 2>/dev/null; then
			    echo "DESCONNECTADA"
			else
			    echo "CONNECTADA"
			fi 
		fi
}


######################################################################
###  MAIN
######################################################################

MSG="falta [iniciar, aturar, configurar ,estat]"

# Comprovem que hi hagi almenys un argument (la opció)
if [ $# -lt 1 ]; then
  echo "$MSG"
  exit 1
fi

OPCIO_1=$1
shift

# Fem switch per executar la funció que toca
case "$OPCIO_1" in
  iniciar | start)
    fnc_iniciar  $@
    ;;
  aturar | stop)
    fnc_aturar	$@
    ;; 
  configurar | conf) 
    fnc_configurar $@
    ;;
  estat | status) 
    fnc_estat $@
    ;;
  *)
    echo "$MSG"
    ;;
esac

