#!/bin/bash

source /usr/local/LosChichos/conf/variables.conf
source "$DIR/$PROJECTO/$DIR_CONF/$CONF_IFWAN"

######################################################################
###  Funcions
######################################################################
fnc_estado_aislar()
{
VLAN_ID="$2"
if iptables -C vlan_$VLAN_ID -j DMZ_ISOLATION 2>/dev/null; then
    echo "$ACTIVADO"
else
    echo "$DESACTIVADO"
fi

}
fnc_iniciar()
{
	fnc_aturar >/dev/null 2>&1
	echo "Iniciar"	
		
	
	for linia in $(grep -v '#' "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"); do
	    nom=$(echo "$linia"|cut -d';' -f1)
	    ip=$(echo "$linia"|cut -d';' -f3)
		id=$(echo "$linia" | cut -d';' -f2)

		#Creando cadena de VLANS FORWARD
	    iptables -N $nom
	    iptables -A FORWARD -s $ip -j $nom

		#Creando cadena de VLANs INPUT
		iptables -N INPUT$nom
		iptables -A INPUT -s $ip -j INPUT$nom

		# Si no es vlan admin bloquea conexion al router
		if [ "$id" != "1" ]; then
			iptables -A INPUT$nom -s $ip -m conntrack --ctstate NEW -j DROP
		fi 	    
	done

	# Cadena ports_wls
	iptables -N ports_wls
	for linia in $(grep -v '#' "$DIR/$PROJECTO/$DIR_CONF/$PORTS_WLS"); do
	    prot=$(echo "$linia"|cut -d';' -f1)
	    num_port=$(echo "$linia"|cut -d';' -f2)
		if [ "$prot" = "icmp" ]; then #si le introduces icmp en el protocolo automaticamente te permite los pings
			iptables -A ports_wls -p icmp --icmp-type echo-request -j ACCEPT
			iptables -A ports_wls -p icmp --icmp-type echo-reply -j ACCEPT
		else
		iptables -A ports_wls -p $prot --dport $num_port -j ACCEPT
		fi
	done
	iptables -A ports_wls -j DROP

	## Cadena DMZ_ISOLATION

	iptables -t filter -N DMZ_ISOLATION 2>/dev/null
	iptables -t filter -F DMZ_ISOLATION


	iptables -A DMZ_ISOLATION -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
	iptables -A DMZ_ISOLATION -i "$enp" -m conntrack --ctstate NEW -j ACCEPT
	iptables -A DMZ_ISOLATION -m conntrack --ctstate NEW -j DROP



}

fnc_aturar()
{
	echo "Parar"
	iptables -F
	iptables -X
	iptables -P FORWARD ACCEPT
	iptables -P INPUT ACCEPT
	iptables -P OUTPUT ACCEPT
	
	
	resultat=$(cd $DIR/$PROJECTO/$DIR_SCRIPTS/ && ./enrutar status)

	# Comprovem si conté la paraula "ACTIVAT"
	echo "$resultat" | grep -q "$ACTIVADO"

	if [ $? -eq 0 ]; then
		iptables -t nat -F 
		iptables -t nat -X
		cd $DIR/$PROJECTO/$DIR_SCRIPTS/ && ./enrutar start
	else
		iptables -t nat -F 
		iptables -t nat -X
	fi	
}


fnc_configurar()
{	
	
	echo "Configuracio"
	
	ARG_1=$1
	shift
			
	# Fem switch per executar la funció que toca
	case "$ARG_1" in
	  	desconnectar)
	        linia=$(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
			vid=$( echo $linia | cut -d';' -f2)
	        if [ -z "$nom" ]; then
		    	echo "Error no existeix vlan $1"
			else
		    	iptables -F $nom

			#Añadimos las excepciones de ips_wls.conf
			for ipwls in $(grep -v '#' "$DIR/$PROJECTO/$DIR_CONF/$IPS_WLS" | grep "^$vid;"); do
				ip=$(echo "$ipwls"|cut -d';' -f2)
				mac=$(echo "$ipwls"|cut -d';' -f3)
				iptables -A $nom -s $ip -m mac --mac-source $mac -j ACCEPT
			
			done

		    iptables -A $nom -j DROP
			fi
	  	;;
	  	connectar)
	        linia=$(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
			IP_VLAN=$(echo "$linia" | cut -d';' -f3)
			ID_VLAN=$(echo "$linia" | cut -d';' -f2)
	        if [ -z "$nom" ]; then
		    	echo "Error no existeix vlan $1"
				exit 1
			fi
			iptables -F $nom
	  	;;

		connectar_admin)
			linia=$(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
			IP_VLAN=$(echo "$linia" | cut -d';' -f3)
			ID_VLAN=$(echo "$linia" | cut -d';' -f2)
			if [ -z "$nom" ]; then
		    	echo "Error no existeix vlan $1"
			else
			iptables -D INPUT$nom -s $IP_VLAN -m conntrack --ctstate NEW -j DROP
			fi
		;;
		desconectar_admin)
			linia=$(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
			IP_VLAN=$(echo "$linia" | cut -d';' -f3)
			ID_VLAN=$(echo "$linia" | cut -d';' -f2)
			iptables -A INPUT$nom -s $IP_VLAN -m conntrack --ctstate NEW -j DROP
		;;
		connectar_port_wls)
	        linia=$(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
	        if [ -z "$nom" ]; then
		    	echo "Error no existeix vlan $1"
			else
			iptables -F $nom
			# IPs Privilegiadas
			vid=$( echo $linia | cut -d';' -f2)
			for ipwls in $(grep -v '#' "$DIR/$PROJECTO/$DIR_CONF/$IPS_WLS" | grep "^$vid;"); do
				ip=$(echo "$ipwls"|cut -d';' -f2)
				mac=$(echo "$ipwls"|cut -d';' -f3)
				iptables -A $nom -s $ip -m mac --mac-source $mac -j ACCEPT
			
			done

			iptables -A $nom -j ports_wls	#La añadimos a FORWARD
			iptables -A INPUT$nom -j ports_wls #La añadimos a INPUT

		fi	        
	  	;;
		afegir_port_wls)
	  	echo "$1;$2;" >> "$DIR/$PROJECTO/$DIR_CONF/$PORTS_WLS"
	    ;;
		eliminar_port_wls)
	        PROTO="$1"
			PORT="$2"
			sed -i "/^${PROTO};${PORT};$/d" "$DIR/$PROJECTO/$DIR_CONF/$PORTS_WLS"
	    ;;  
	  	afegir_ip_wls)
	  		echo "$1;$2;$3;" >> "$DIR/$PROJECTO/$DIR_CONF/$IPS_WLS"
	    ;;
	  	eliminar_ip_wls)
	        VID="$1"
			IP="$2"
			MAC="$3"
			sed -i "/^${VID};${IP};${MAC};$/d" "$DIR/$PROJECTO/$DIR_CONF/$IPS_WLS"
	    ;;
		aislar)
			VLAN_ID="$1"

    		linia=$(grep ";$VLAN_ID;" "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF")
    		nom=$(echo "$linia" | cut -d';' -f1)
			IP_VLAN=$(echo "$linia" | cut -d';' -f3)

    		if [ -z "$nom" ]; then
        		echo "Error: no existeix vlan $VLAN_ID"
        		return 1
    		fi

			iptables -A INPUT -s $IP_VLAN -m conntrack --ctstate NEW -j DROP

    		iptables -C vlan_$VLAN_ID -j DMZ_ISOLATION 2>/dev/null || \
    		iptables -A vlan_$VLAN_ID -j DMZ_ISOLATION
			;;
		desaislar)

    		VLAN_ID="$1"

    		linia=$(grep ";$VLAN_ID;" "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF")
    		nom=$(echo "$linia" | cut -d';' -f1)
			IP_VLAN=$(echo "$linia" | cut -d';' -f3)

    		if [ -z "$nom" ]; then
        		echo "Error: no existeix vlan $VLAN_ID"
        		return 1
    		fi

    		if iptables -C vlan_$VLAN_ID -j DMZ_ISOLATION 2>/dev/null; then
        		iptables -D vlan_$VLAN_ID -j DMZ_ISOLATION
    		fi


    		;;

	  *)
	        echo "Error  argumnets conectar, desconectar"
	        ;;
	esac	
	
}


fnc_estat()
{	
	if [ "$1" = "aislar" ]; then
    fnc_estado_aislar $@
	exit 0
	fi

	if [ $# -eq 0 ]; then
		 #echo "$ACTIVAT"
		 #echo "$DESACTIVAT"
		 echo MAIN
		 iptables -nvL --line-numbers
		 echo
		 echo
		 echo NAT	 
		 iptables -t nat -nvL --line-numbers
		 exit 1
	fi
	
	        linia=$(cat "$DIR/$PROJECTO/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
	        nom=$( echo $linia | cut -d';' -f1)
			ip=$( echo $linia | cut -d';' -f3)
	        if [ -z "$nom" ]; then
		    echo "Error no existeix vlan $1"
		else
			if ! sudo iptables -L "$nom" -n >/dev/null 2>&1; then
    			echo "Error: no existe la cadena de reglas"
    			exit 1
			fi
		    if sudo iptables -C $nom -j DROP 2>/dev/null; then
			    echo "DESCONNECTADA"
			elif sudo iptables -S "$nom" 2>/dev/null | grep -q "\-j ports_wls"; then
   				echo "CONNECTADA-PORTS-WLS"
			elif sudo iptables -C $nom -j DMZ_ISOLATION 2>/dev/null; then
				echo "CONNECTADA-AISLADA"
			elif ! sudo iptables -C INPUT$nom -s "$ip" -m conntrack --ctstate NEW -j DROP 2>/dev/null; then
				# Iptables -A INPUT$nom -s $ip -m conntrack --ctstate NEW -j DROP
				echo "CONNECTADA-CON-ADMIN"
			else
			    echo "CONNECTADA"
			fi 
		fi
}


######################################################################
###  MAIN
######################################################################

MSG="falta [iniciar, aturar, configurar ,estat]"

# Comprovem que hi hagi almenys un argument (la opció)
if [ $# -lt 1 ]; then
  echo "$MSG"
  exit 1
fi

OPCIO_1=$1
shift

# Fem switch per executar la funció que toca
case "$OPCIO_1" in
  iniciar | start)
    fnc_iniciar  $@
    ;;
  aturar | stop)
    fnc_aturar	$@
    ;; 
  configurar | conf) 
    fnc_configurar $@
    ;;
  estat | status) 
    fnc_estat $@
    ;;
  *)
    echo "$MSG"
    ;;
esac

