#!/bin/bash

source /usr/local/LosChichos/conf/variables.conf
source $DIR/$PROJECTO/$DIR_CONF/$FUNC

######################################################################
###  Funcions
######################################################################

# saber si la targeta suporta mode AP
# iw list | grep -A 10 "Supported interface modes" | grep "* AP"
# busqueda millor canal
# iw dev wlp1s0 scan | grep DS
# verue el xipset
# lspci -nnk | grep -A3 -i network


fnc_iniciar() {
	if [[ "$(fnc_estat)" =~ ^$ACTIVADO* ]]; then
		echo "Wifi ya esta iniciado"
		return 1
	fi	

	if iwconfig 2>/dev/null | grep -q "IEEE 802.11"; then
		echo "Iniciando wifi"
		( 
			source "$DIR/$PROJECTO/$DIR_CONF/$WIFI_HOSTAPD_CONF"
			source "$DIR/$PROJECTO/$DIR_CONF/$WIFI_CONF"
			if ! fnc_int_wifi_suporta_ap $interface; then
				echo "La interfaz $interface no soporta modo AP"
				return 1
			fi
			pkill hostapd
			if lspci -nnk | grep -A3 -i network| grep -q "Driver: rtl8192ce"; then
				ip link set $interface down
				modprobe -r rtl8192ce
				modprobe -r rtl8192c_common
				modprobe -r rtlwifi
				modprobe rtl8192ce
				iw dev $interface set type __ap
			ip l s dev $interface up
			fi
			
			hostapd -B $DIR/$PROJECTO/$DIR_CONF/$WIFI_HOSTAPD_CONF

			ip l s dev $interface up
			ip a a $wifi_ip dev $interface

			fnc_estat
			
		)
	else
		echo "No hay tarjeta inalambrica"
	fi
	
}

fnc_aturar() {
	if [[ "$(fnc_estat)" =~ ^$DESACTIVADO* ]]; then
		echo "Wifi ya esta parado"
		return 1
	fi

	echo "Parando wifi"
	pkill hostapd
	(
		source "$DIR/$PROJECTO/$DIR_CONF/$WIFI_HOSTAPD_CONF"
		source "$DIR/$PROJECTO/$DIR_CONF/$WIFI_CONF"  
		ip l s dev $interface down		
		ip a d $wifi_ip dev $interface
		echo "parando $interface"
		
		# Comprovem si hi ha que reiniciar el dhcp
		
	)
}

fnc_guardar_wifi_ip() {

	if [ $# -lt 1 ]; then
		echo "faltan parametros ip"
		return 1
	fi

	ip_wifi=$1
	
	if ! fnc_validar_ip_host $ip_wifi; then
		echo "IP host $ip_wifi no valida"
		return 1
	fi

	source "$DIR/$PROJECTO/$DIR_CONF/$WIFI_CONF"
	
	ip_inicial=$(fnc_primera_ip_de_host $ip_wifi)	
	ip_final=$(fnc_darrera_ip_de_host $ip_wifi)

	{
		echo "wifi_ip=$ip_wifi"
		echo "wifi_ip_inicial=$ip_inicial"
		echo "wifi_ip_final=$ip_final"
		echo "wifi_gateway=$ip_inicial"
		echo "wifi_ip_dns1=$ip_inicial"
		echo "wifi_dhcp_actiu=$wifi_dhcp_actiu"
		echo "wifi_portal_captiu=$wifi_portal_captiu"
	} > "$DIR/$PROJECTO/$DIR_CONF/$WIFI_CONF"
	
	echo "Guardando wifi ip"
}

fnc_guardar_wifi_conf() {
	if [ $# -lt 7 ]; then
		echo "faltan parametros ip, inicio, final, gateway, dns1, ACTIVADO|DESACTIVADO, ACTIVADO|DESACTIVADO"
		return 1
	fi	
	
	if ! fnc_validar_ip_host $1; then
		echo "IP host $1 no valida"
		return 1
	fi
	if ! fnc_validar_ip $2; then
		echo "IP inicial $2 no valida"
		return 1
	fi
	if ! fnc_validar_ip $3; then
		echo "IP final $3 no valida"
		return 1
	fi
	if ! fnc_validar_ip $4; then
		echo "IP gateway $4 no valida"
		return 1
	fi
	if ! fnc_validar_ip $5; then
		echo "IP dns1 $5 no valida"
		return 1
	fi
	if [[ "$6" != "$ACTIVADO" && "$6" != "$DESACTIVADO" ]]; then
		echo "DHCP $6 no valida"
		return 1
	fi
	if [[ "$7" != "$ACTIVADO" && "$7" != "$DESACTIVADO" ]]; then
		echo "Portal Captivo $7 no valida"
		return 1
	fi

	{
		echo "wifi_ip=$1"
		echo "wifi_ip_inicial=$2"
		echo "wifi_ip_final=$3"
		echo "wifi_gateway=$4"
		echo "wifi_ip_dns1=$5"
		echo "wifi_dhcp_actiu=$6"
		echo "wifi_portal_captiu=$7"
	} > "$DIR/$PROJECTO/$DIR_CONF/$WIFI_CONF"

	echo "Guardando configuracion wifi"
}

fnc_guardar_wifi_hostapd_conf() {

	echo "ahora a guardar hostapd"
	echo "$@"

	if [ $# -lt 12 ]; then
		echo "faltan parametros interface, driver, ssid, hw_mode, channel, auth_algs, ignore_broadcast_ssid, ap_isolate, wpa, wpa_passphrase, wpa_key_mgmt, rsn_pairwise"
		return 1
	fi
	
	interface=$1
	driver=$2
	ssid=$3
	hw_mode=$4
	channel=$5
	auth_algs=$6
	ignore_broadcast_ssid=$7
	ap_isolate=$8
	wpa=$9
	wpa_passphrase=${10}
	wpa_key_mgmt=${11}
	rsn_pairwise=${12}
	
	{
		echo "interface=$interface"
		echo "driver=$driver"
		echo "ssid=$ssid"
		echo "hw_mode=$hw_mode"
		echo "channel=$channel"
		echo "auth_algs=$auth_algs"
		echo "ignore_broadcast_ssid=$ignore_broadcast_ssid"		
		echo "ap_isolate=$ap_isolate"
		echo "wpa=$wpa"
		echo "wpa_passphrase=$wpa_passphrase"
		echo "wpa_key_mgmt=$wpa_key_mgmt"
		echo "rsn_pairwise=$rsn_pairwise"
		
	} > "$DIR/$PROJECTO/$DIR_CONF/$WIFI_HOSTAPD_CONF"
}

fnc_mostrar_wifi_hostapd_conf() {
	source "$DIR/$PROJECTO/$DIR_CONF/$WIFI_HOSTAPD_CONF"
	echo "$interface;$ssid;$hw_mode;$channel;$ipwifi;$masc;$ap_isolate;$wpa_passphrase;$wpa_key_mgmt;"
}

fnc_mostrar_wifi_conf() {
	source "$DIR/$PROJECTO/$DIR_CONF/$WIFI_CONF"
	source "$DIR/$PROJECTO/$DIR_CONF/$WIFI_HOSTAPD_CONF"
	echo "$interface;$wifi_ip;$wifi_ip_inicial;$wifi_ip_final;$wifi_gateway;$wifi_ip_dns1;$wifi_dhcp_actiu;"
}



fnc_configurar() {
	local ACCIO=$1
	shift

	case "$ACCIO" in
		"guardar_wifi_conf")
			fnc_guardar_wifi_conf $@
			;;
		"guardar_wifi_ip")
			fnc_guardar_wifi_ip $@
			;;
		"guardar_wifi_hostapd_conf")
			fnc_guardar_wifi_hostapd_conf $@
			;;
		"mostrar_wifi_conf")
			fnc_mostrar_wifi_conf $@
			;;
		"mostrar_wifi_hostapd_conf")
			fnc_mostrar_wifi_hostapd_conf $@
			;;
		*)
			echo "falta [guardar_wifi_conf, guardar_wifi_ip, guardar_wifi_hostapd_conf, mostrar_wifi_conf, mostrar_wifi_hostapd_conf]"
			;;
	esac
	
}

fnc_estat() {
	# Comprova si el procés hostapd està en execució
	if pgrep -x "hostapd" > /dev/null
	then
	    echo "$ACTIVADO"
		echo " "
		iw dev
	    echo "hostapd esta activo."
	else
	    echo "$DESACTIVADO"
	    echo "hostapd no esta activo."
	fi
}

######################################################################
###  MAIN
######################################################################

MSG="falta [iniciar, aturar, configurar ,estat]"

# Comprovem que hi hagi almenys un argument (la opció)
if [ $# -lt 1 ]; then
	echo "$MSG"
	exit 1
fi

OPCIO_1=$1
shift

# Fem switch per executar la funció que toca
case "$OPCIO_1" in
iniciar)
	fnc_iniciar $@
	;;
aturar)
	fnc_aturar $@
	;;
configurar)
	fnc_configurar $@
	;;
estat)
	fnc_estat $@
	;;
*)
	echo "$MSG"
	;;
esac
